spring:
  application:
    name: demo
  profiles:
    active:
      - mybatis
      - dubbo
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/activiti?useSSL=false&serverTimezone=UTC
      username: root
      password: 1qaz2wsx
      name: ds001
      filters:
      filter:
        log4j2:
          enabled: true
        wall:
          enabled: true
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 3000
          db-type: mysql
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
  data:
    elasticsearch:
      repositories:
        enabled: false

logging:
  level:
    root: info
    com.alibaba.dubbo: info
    org.springframework.boot.autoconfigure.condition: debug
    org.elasticsearch: debug
management:
  endpoint:
    beans:
      enabled: true
  health:
    redis:
      enabled: true
    db:
      enabled: true

