dubbo:
  config:
    multiple: true
  scan:
    basePackages: com.seriousplay.productivity
  applications:
    demo:
      id: demo
      name: demo
  protocols:
    dubbo:
      id: dubbo
      name: dubbo
      port: 20880
      serialization: kryo
    rest:
      id: rest
      name: rest
      port: 20881
      server: netty
      contextpath: rest
  registries:
    zookeeper:
      address: zookeeper://localhost:2181

