dubbo:
  config:
    multiple: true
  scan:
    basePackages: com.seriousplay.productivity
  applications:
    demo:
      id: demo
      name: demo
  protocols:
    dubbo:
      id: dubbo
      name: dubbo
      port: 20880
  registries:
    zookeeper:
      address: zookeeper://localhost:2181

  protocol:
    serialization: kryo
